# Generated by Django 4.2.3 on 2023-07-26 23:34

from django.db import migrations


def convert_charfield_to_integer(apps, schema_editor):
    YourModel = apps.get_model('course', 'Course')
    for obj in YourModel.objects.all():
        obj.level = 1
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(convert_charfield_to_integer),
    ]
