# Generated by Django 4.2.3 on 2023-07-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitems',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
